import type { Client } from "ssh2";
import { sshExec, sshWriteFile } from "./ssh-exec";
import { slugifyName } from "./types";

interface DefaultConfigOptions {
	projectName: string;
	repoDir: string;
}

/**
 * Check if a devcontainer.json already exists in the repo.
 * Returns the path if found, null otherwise.
 */
export async function detectExistingConfig(
	client: Client,
	repoDir: string,
): Promise<string | null> {
	// Check standard locations
	const paths = [
		`${repoDir}/.devcontainer/devcontainer.json`,
		`${repoDir}/.devcontainer.json`,
	];

	for (const path of paths) {
		const result = await sshExec(client, `test -f ${path}`, { timeout: 5_000 });
		if (result.code === 0) return path;
	}

	return null;
}

/**
 * Generate a default devcontainer.json for repos without one.
 * Written to .devcontainer/devcontainer.json and excluded from git.
 */
export async function generateDefaultConfig(
	client: Client,
	opts: DefaultConfigOptions,
): Promise<string> {
	const slug = slugifyName(opts.projectName);

	const config = {
		name: opts.projectName,
		image: "mcr.microsoft.com/devcontainers/base:ubuntu",
		workspaceMount: `source=\${localWorkspaceFolder},target=/workspaces/${slug},type=bind`,
		workspaceFolder: `/workspaces/${slug}`,
		features: {
			"ghcr.io/devcontainers/features/git:1": {},
		},
		postCreateCommand: `git config --global --add safe.directory /workspaces/${slug}`,
		remoteUser: "vscode",
		customizations: {
			superset: { generated: true, version: 1 },
		},
	};

	const configDir = `${opts.repoDir}/.devcontainer`;
	const configPath = `${configDir}/devcontainer.json`;

	// Create .devcontainer directory
	await sshExec(client, `mkdir -p ${configDir}`, { timeout: 5_000 });

	// Write config via stdin pipe (no escaping needed)
	const content = `${JSON.stringify(config, null, 2)}\n`;
	await sshWriteFile(client, configPath, content);

	// Exclude from git (local only, not committed)
	await sshExec(
		client,
		`grep -qxF '.devcontainer/' ${opts.repoDir}/.git/info/exclude 2>/dev/null || echo '.devcontainer/' >> ${opts.repoDir}/.git/info/exclude`,
		{ timeout: 5_000 },
	);

	return configPath;
}

/**
 * Check if an existing devcontainer.json was generated by Superset.
 */
export async function isGeneratedConfig(
	client: Client,
	configPath: string,
): Promise<boolean> {
	const result = await sshExec(
		client,
		`grep -q '"superset"' ${configPath} && grep -q '"generated": true' ${configPath}`,
		{ timeout: 5_000 },
	);
	return result.code === 0;
}
